[package]
name = "residuals"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra = "0.34.1"
ndarray  = "0.17.1"
ndarray-stats="0.6.0"
statrs   = "0.18.0"
plotters = "0.3.7"
indicatif= "0.18.0"
toml	 = "0.9.8"
serde = { version = "1.0.228", features = ["derive"] }
