[residuals]
# Z of GEMs. Increasing or decreasing order.
z = [0.0, 180.0, 700.0]

# set path to data. e.g "/home/foo/bar_data/"
inpath = "/home/me/syncthing/homework/lab/sorting_output"
 
#set run number of input AND output file. file is in format 'output_file_run_{infile}.txt'/'x_y_corrected_{run_num}.txt' respectively
run_num = "4162_4177"

#set path to output
outpath = "/home/me/syncthing/homework/lab/residual_output"
#set run number of output file. file is in format x_y_corrected_{run_num}.txt

# set true to calculate residuals and align GEMs
exec = false

[angles]
#set path to output
outpath = "/home/me/syncthing/homework/lab/angles_output"
#set run number of output file. file is in format angles_{run_num}.txt
run_num = "4162_4177"

# set true to calculate angle distribution
exec = true


